name: testing

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .npmrc for github packages
      run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.ACCESS_PACKAGES }}" >> ~/.npmrc
    - name: Set up node js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Install dependencies
      run: npm install
      env:
        CI: true
    - name: Build dependencies
      run: npm run build --if-present
    - name: Run Lint Test
      run: npm run lint
    - name: Allow Docker access to github packages
      uses: docker/login-action@v1
      with:
        username: ${{ github.actor }}
        password: ${{ secrets.ACCESS_PACKAGES }}
        registry: docker.pkg.github.com
    - name: Start surfer
      run: docker run --publish 3030:3030 --detach docker.pkg.github.com/datacraft-dsc/surfer/surfer:latest
    - name: Start invokable-py test server
      run: docker run --publish 9090:9090 --detach docker.pkg.github.com/datacraft-dsc/invokable-py/invokable-py:release
    - name: Wait for surfer
      run: docker run --network host docker.pkg.github.com/datacraft-dsc/surfer/surfer:latest ./scripts/wait_for_surfer.sh
    - name: Wait for survers to load...
      run: sleep 30
    - name: Test
      run: npm test
      env:
        CI: true
